# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: random.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'random.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0crandom.proto\"\xee\x02\n\x06random\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12\x1e\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\x0e.random.Nested\x1a\xb3\x02\n\x06Nested\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x12&\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\x16.random.Nested.Nested2\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\t\x1a\xe0\x01\n\x07Nested2\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x03\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x03\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\t\x12\x0e\n\x06\x66ield5\x18\x05 \x01(\x03\x12\x0e\n\x06\x66ield6\x18\x06 \x01(\x05\x12\x0e\n\x06\x66ield7\x18\x07 \x01(\x05\x12.\n\x06\x66ield8\x18\x08 \x01(\x0b\x32\x1e.random.Nested.Nested2.Nested3\x12\x0e\n\x06\x66ield9\x18\t \x01(\x05\x1a)\n\x07Nested3\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x05\x12\x0e\n\x06\x66ield3\x18\x03 \x01(\x05\x1a\n\n\x08Nested14b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'random_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANDOM']._serialized_start=17
  _globals['_RANDOM']._serialized_end=383
  _globals['_RANDOM_NESTED']._serialized_start=76
  _globals['_RANDOM_NESTED']._serialized_end=383
  _globals['_RANDOM_NESTED_NESTED2']._serialized_start=159
  _globals['_RANDOM_NESTED_NESTED2']._serialized_end=383
  _globals['_RANDOM_NESTED_NESTED2_NESTED3']._serialized_start=330
  _globals['_RANDOM_NESTED_NESTED2_NESTED3']._serialized_end=371
  _globals['_RANDOM_NESTED_NESTED2_NESTED14']._serialized_start=373
  _globals['_RANDOM_NESTED_NESTED2_NESTED14']._serialized_end=383
# @@protoc_insertion_point(module_scope)
