# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Team_Chat_Startup.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'Team_Chat_Startup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17Team_Chat_Startup.proto\"\x8d\x01\n\x11team_chat_startup\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12*\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32\x19.team_chat_startup.nested\x1a<\n\x06nested\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x13\n\x0bteam_packet\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Team_Chat_Startup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEAM_CHAT_STARTUP']._serialized_start=28
  _globals['_TEAM_CHAT_STARTUP']._serialized_end=169
  _globals['_TEAM_CHAT_STARTUP_NESTED']._serialized_start=109
  _globals['_TEAM_CHAT_STARTUP_NESTED']._serialized_end=169
# @@protoc_insertion_point(module_scope)
