# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wlxd_spam.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'wlxd_spam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwlxd_spam.proto\"\xe7\x04\n\x0fWLXDSkwadPacket\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\x05\x12(\n\x06\x66ield2\x18\x02 \x01(\x0b\x32\x18.WLXDSkwadPacket.Details\x1a\x99\x04\n\x07\x44\x65tails\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x63ountry_code\x18\x02 \x01(\t\x12\x0f\n\x07status1\x18\x03 \x01(\x05\x12\x0f\n\x07status2\x18\x04 \x01(\x05\x12\x0f\n\x07numbers\x18\x05 \x01(\x0c\x12\x0e\n\x06\x65mpty1\x18\x06 \x01(\t\x12\x0c\n\x04rank\x18\x07 \x01(\x05\x12\x0e\n\x06\x66ield8\x18\x08 \x01(\x05\x12\x0e\n\x06\x66ield9\x18\t \x01(\x05\x12\x13\n\x0bregion_code\x18\n \x01(\t\x12\x0c\n\x04uuid\x18\x0b \x01(\x0c\x12\x0f\n\x07\x66ield12\x18\x0c \x01(\x05\x12\x14\n\x0crepeated_uid\x18\r \x01(\x03\x12\x0f\n\x07\x66ield16\x18\x10 \x01(\x05\x12\x0f\n\x07\x66ield18\x18\x12 \x01(\x05\x12\x0f\n\x07\x66ield19\x18\x13 \x01(\x05\x12\x32\n\x07\x66ield20\x18\x14 \x01(\x0b\x32!.WLXDSkwadPacket.Details.Nested20\x12\x0f\n\x07\x66ield23\x18\x17 \x01(\x0c\x12\x0e\n\x06\x61vatar\x18\x18 \x01(\x05\x12/\n\x07\x66ield26\x18\x1a \x01(\x0b\x32\x1e.WLXDSkwadPacket.Details.Empty\x12/\n\x07\x66ield28\x18\x1c \x01(\x0b\x32\x1e.WLXDSkwadPacket.Details.Empty\x1a\x39\n\x08Nested20\x12\x0e\n\x06server\x18\x01 \x01(\t\x12\x0c\n\x04ping\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x1a\x07\n\x05\x45mptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wlxd_spam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WLXDSKWADPACKET']._serialized_start=20
  _globals['_WLXDSKWADPACKET']._serialized_end=635
  _globals['_WLXDSKWADPACKET_DETAILS']._serialized_start=98
  _globals['_WLXDSKWADPACKET_DETAILS']._serialized_end=635
  _globals['_WLXDSKWADPACKET_DETAILS_NESTED20']._serialized_start=569
  _globals['_WLXDSKWADPACKET_DETAILS_NESTED20']._serialized_end=626
  _globals['_WLXDSKWADPACKET_DETAILS_EMPTY']._serialized_start=628
  _globals['_WLXDSKWADPACKET_DETAILS_EMPTY']._serialized_end=635
# @@protoc_insertion_point(module_scope)
